// Generated by gencpp from file autolabor_first/addInts.msg
// DO NOT EDIT!


#ifndef AUTOLABOR_FIRST_MESSAGE_ADDINTS_H
#define AUTOLABOR_FIRST_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <autolabor_first/addIntsRequest.h>
#include <autolabor_first/addIntsResponse.h>


namespace autolabor_first
{

struct addInts
{

typedef addIntsRequest Request;
typedef addIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addInts
} // namespace autolabor_first


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autolabor_first::addInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::autolabor_first::addInts&) { return value(); }
};

template<>
struct DataType< ::autolabor_first::addInts > {
  static const char* value()
  {
    return "autolabor_first/addInts";
  }

  static const char* value(const ::autolabor_first::addInts&) { return value(); }
};


// service_traits::MD5Sum< ::autolabor_first::addIntsRequest> should match
// service_traits::MD5Sum< ::autolabor_first::addInts >
template<>
struct MD5Sum< ::autolabor_first::addIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autolabor_first::addInts >::value();
  }
  static const char* value(const ::autolabor_first::addIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autolabor_first::addIntsRequest> should match
// service_traits::DataType< ::autolabor_first::addInts >
template<>
struct DataType< ::autolabor_first::addIntsRequest>
{
  static const char* value()
  {
    return DataType< ::autolabor_first::addInts >::value();
  }
  static const char* value(const ::autolabor_first::addIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autolabor_first::addIntsResponse> should match
// service_traits::MD5Sum< ::autolabor_first::addInts >
template<>
struct MD5Sum< ::autolabor_first::addIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autolabor_first::addInts >::value();
  }
  static const char* value(const ::autolabor_first::addIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autolabor_first::addIntsResponse> should match
// service_traits::DataType< ::autolabor_first::addInts >
template<>
struct DataType< ::autolabor_first::addIntsResponse>
{
  static const char* value()
  {
    return DataType< ::autolabor_first::addInts >::value();
  }
  static const char* value(const ::autolabor_first::addIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOLABOR_FIRST_MESSAGE_ADDINTS_H
