// Generated by gencpp from file autolabor_first/addIntsResponse.msg
// DO NOT EDIT!


#ifndef AUTOLABOR_FIRST_MESSAGE_ADDINTSRESPONSE_H
#define AUTOLABOR_FIRST_MESSAGE_ADDINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autolabor_first
{
template <class ContainerAllocator>
struct addIntsResponse_
{
  typedef addIntsResponse_<ContainerAllocator> Type;

  addIntsResponse_()
    : sum(0)  {
    }
  addIntsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::autolabor_first::addIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autolabor_first::addIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct addIntsResponse_

typedef ::autolabor_first::addIntsResponse_<std::allocator<void> > addIntsResponse;

typedef boost::shared_ptr< ::autolabor_first::addIntsResponse > addIntsResponsePtr;
typedef boost::shared_ptr< ::autolabor_first::addIntsResponse const> addIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autolabor_first::addIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autolabor_first::addIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autolabor_first::addIntsResponse_<ContainerAllocator1> & lhs, const ::autolabor_first::addIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autolabor_first::addIntsResponse_<ContainerAllocator1> & lhs, const ::autolabor_first::addIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autolabor_first

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autolabor_first::addIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autolabor_first::addIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autolabor_first::addIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autolabor_first::addIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolabor_first::addIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolabor_first::addIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autolabor_first::addIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::autolabor_first::addIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::autolabor_first::addIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autolabor_first/addIntsResponse";
  }

  static const char* value(const ::autolabor_first::addIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autolabor_first::addIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 服务器响应发送的数据\n"
"int32 sum\n"
"\n"
;
  }

  static const char* value(const ::autolabor_first::addIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autolabor_first::addIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autolabor_first::addIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autolabor_first::addIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOLABOR_FIRST_MESSAGE_ADDINTSRESPONSE_H
